algoritmo "competiçãoSE"
// Função :
// Autor :
// Data : 08/06/2021
// Seção de Declarações 
var

idade: inteiro
altura: real

inicio
escreval ("Qual a sua idade?")
leia (idade)

escreval ("Qual sua altura?")
leia (altura)

se (altura >= 1.75) e (idade >= 18) entao
    escreval ("Você pode competir!")
senao
    escreval ("Você não pode participar da competição")
fimse
fimalgoritmo
