algoritmo "impar_parSE"
// Função : Usar condicionais para definir se um número é impar ou par
// Autor :  Laura Esther
// Data : 08/06/2021
// Seção de Declarações 
var

num: inteiro

inicio
escreval ("Digite um número")
leia (num)

se ((num mod 2) = 0) entao
    escreval ("Esse é um número par")
fimse

se ((num mod 2) = 1) entao
    escreval ("Esse é um número impar")
fimse

fimalgoritmo
