algoritmo "inc_fin"
// Função :  Fazer com que imprima os números de um certo número até outro
// Autor : Laura Esther
// Data : 14/08/2021
// Seção de Declarações 
var

cont, inc, fin: inteiro

inicio

escreval ("Informe o número de onde a contagem irá começar")
leia (inc)

escreval ("Informe o número onde a contagem irá terminar")
leia (fin)

para cont de inc ate fin faca
     escreval(cont)
fimpara

fimalgoritmo
