algoritmo "melhor_escola"
// Função : perguntar ao usuário qual a melhor escola de Ribeirão
// Autor : Laura Esther
// Data : 14/08/2021
// Seção de Declarações 
var

escola: caractere

inicio

repita
     escreval ("Qual a melhor escola de Ribeirão Pires")
     leia (escola)
ate (escola = "Etec MCM") ou (escola = "etec mcm") ou (escola = "ETEC MCM")ou (escola = "Etec Maria Cristina Medeiros") ou (escola = "Etec mcm")

fimalgoritmo
