algoritmo "estoque_peca"
// Função : calcular o estoque medio de uma peca
// Autor :  Laura Esther
// Data : 29/03/2021
// Seção de Declarações 
var

qntdmin, qntdmax, estoquemedio: real

inicio
// entrada
escreval ("Digite a quantidade minina de pecas:")
leia (qntdmin)

escreval ("Digite a quantidade maxima de pecas:")
leia (qntdmax)

// processamento
estoquemedio <- (qntdmin + qntdmax)/2)

// saida
escreval ("O estoque medio e:", estoquemedio)


fimalgoritmo
