algoritmo "valor_peca"
// Função : caluclar o valor total de uma venda de pecas
// Autor : Laura Esther
// Data : 29/03/2021
// Seção de Declarações 
var
qntd: inteiro
valor, vt: real

inicio
// entrada
escreval ("Digite o valor da peca:")
leia (valor)

escreval ("Digite a quantidade comprada:")
leia (qntd)

//processamento
vt <- qntd*valor

//saida
escreval ("O valor total da sua compra e:", vt)

fimalgoritmo
