algoritmo "laços"
// Função : Exemplificar todos os laços de repetição
// Autor : Laura Esther
// Data : 28/07/2021
// Seção de Declarações 
var

cont: inteiro

inicio

//para contar todos os números ímpares até 30
para cont de 1 ate 30 passo 2 faca
      escreval (cont)
fimpara

cont <- 1

enquanto (cont < 30) faca
       escreval(cont)
       cont <- cont+2
fimenquanto

cont <- 1
repita
      escreval(cont)
      cont <- cont+2
ate (cont > 29)

fimalgoritmo
