algoritmo "areatriangulo"
// Função :  calcular a area do triangulo
// Autor :   Laura
// Data : 02/03/2021
// Seção de Declarações 
var

area, base, alt: real

inicio
// Seção de Comandos 

escreval("digite a base do triangulo retangulo")
leia(base)

escreval("digite a altura do triangulo retangulo")
leia(alt)

//Processamento

area <- (base*alt)/2

//Saida

escreval("A area do triangulo retangulo e: ", area, "m2")



fimalgoritmo
